version: "3"
services:
  web:
    image: noron596/uzduotis-1:nginx
    volumes:
      - "./:/main/"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
  php:
     image: noron596/uzduotis-1:symfony-php-pdosql
     volumes:
       - "./:/main/"
  mysql:
     image: noron596/uzduotis-1:mysql-5.6
     volumes:
       - "./:/main/"
       - "./mysql-database/conf.d:/etc/mysql/conf.d"
       - "./mysql-database/:/var/lib/mysql:rw"
     environment:
       - MYSQL_ROOT_HOST=%
       - MYSQL_DATABASE=baze
       - MYSQL_ROOT_PASSWORD=my_secret_pw
       - MYSQL_USER=norma
       - MYSQL_PASSWORD=123
     ports:
       - "3306:3306"
